"""Remove coluna foto de users

Revision ID: 7b3c75238c64
Revises: e623beda9fa5
Create Date: 2025-08-01 13:03:50.399271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3c75238c64'
down_revision: Union[str, Sequence[str], None] = 'e623beda9fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foto', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
