"""Mensagem da migration

Revision ID: 9266094679df
Revises: 
Create Date: 2025-07-15 15:59:41.789171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9266094679df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('medicos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pronomeTratamento', postgresql.ENUM('Dr.', 'Dra.', name='pronome_tratamento'), autoincrement=False, nullable=False),
    sa.Column('especialidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('crm', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tipoContratacao', postgresql.ENUM('CLT', 'PJ', 'Autônomo', name='tipos_contratacao'), autoincrement=False, nullable=False),
    sa.Column('cpfCnpj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('banco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agencia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipoConta', postgresql.ENUM('Corrente', 'Poupança', 'Pagamento', name='tipos_conta'), autoincrement=False, nullable=True),
    sa.Column('percentualRepasse', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('diasAtendimento', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('horarioInicio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('horarioFim', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intervalo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('medicos_pkey'))
    )
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    # ### end Alembic commands ###
