"""reset - schema atual

Revision ID: ada757155eef
Revises: 
Create Date: 2025-07-30 23:16:39.159876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada757155eef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('pacientes', sa.Column('convenio', sa.String(), nullable=True))
    op.add_column('pacientes', sa.Column('foto_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'foto_path')
    op.drop_column('pacientes', 'convenio')
    op.drop_column('pacientes', 'endereco')
    # ### end Alembic commands ###
