"""adiciona endereco e convenio ao paciente

Revision ID: bf7904170cc8
Revises: cea5b382706d
Create Date: 2025-07-29 16:47:55.274541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7904170cc8'
down_revision: Union[str, Sequence[str], None] = 'cea5b382706d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('pacientes', sa.Column('convenio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'convenio')
    op.drop_column('pacientes', 'endereco')
    # ### end Alembic commands ###
