"""Adiciona coluna foto ao usuário

Revision ID: e623beda9fa5
Revises: ada757155eef
Create Date: 2025-07-31 14:27:37.591138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e623beda9fa5'
down_revision: Union[str, Sequence[str], None] = 'ada757155eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto')
    # ### end Alembic commands ###
